const canvas = document.querySelector('#city'); const ctx = canvas.getContext('2d');
let state = { commands:0, commits:0, errors:0, metrics:{cpuPct:0}, districts:{}, buildings:{}, incidents:[] }; let paused = false; let offset = 0;
const $ = (id) => document.querySelector(id); const colors = {violet:'#8a6cff',cyan:'#47d9e4',amber:'#ffb75f',rose:'#ff718f',lime:'#b4e66e'};
function resize(){ const ratio=devicePixelRatio||1; canvas.width=canvas.clientWidth*ratio; canvas.height=canvas.clientHeight*ratio; ctx.setTransform(ratio,0,0,ratio,0,0); draw(); } addEventListener('resize',resize); canvas.addEventListener('pointermove',(e)=>{offset=(e.offsetX/canvas.clientWidth-.5)*26;draw()});
function iso(x,y,z){return [canvas.clientWidth/2+(x-y)*1.3+offset,canvas.clientHeight*.66+(x+y)*.43-z]};
function poly(points,fill,stroke){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function building(x,y,w,d,h,color,health){const a=iso(x,y,0),b=iso(x+w,y,0),c=iso(x+w,y+d,0),e=iso(x,y+d,0),at=iso(x,y,h),bt=iso(x+w,y,h),ct=iso(x+w,y+d,h),et=iso(x,y+d,h);poly([a,b,bt,at],color+'aa');poly([b,c,ct,bt],color+'66');poly([at,bt,ct,et],color);if(health<100){ctx.fillStyle='#ff635d';ctx.beginPath();ctx.arc(at[0],at[1]-8,4,0,Math.PI*2);ctx.fill()}for(let zz=10;zz<h-5;zz+=12){ctx.fillStyle='#fff0a9aa';ctx.fillRect(at[0]+4,at[1]+zz*.34,2,2)}}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#171044');grad.addColorStop(1,'#070615');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);for(let i=-13;i<14;i++){ctx.strokeStyle='#3c306833';ctx.beginPath();const p=iso(i,-12,0),q=iso(i,12,0);ctx.moveTo(...p);ctx.lineTo(...q);ctx.stroke();const r=iso(-12,i,0),s=iso(12,i,0);ctx.beginPath();ctx.moveTo(...r);ctx.lineTo(...s);ctx.stroke()}const structures=Object.values(state.buildings);structures.forEach((b,i)=>{const seed=b.seed||i*17;const x=(seed%10-5)*7,y=(Math.floor(seed/10)%8-4)*7;const district=state.districts[b.districtId];building(x,y,4+(seed%3),4+(seed%2),Math.max(16,(b.targetHeight||4)*5),colors[district?.palette]||colors.violet,b.health||100)});ctx.fillStyle='#ded5ff';ctx.font='11px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';ctx.fillText(`${structures.length} ACTIVE STRUCTURES`,22,h-24)}
function paint(){ $('#commands').textContent=state.commands||0;$('#commits').textContent=state.commits||0;$('#errors').textContent=state.errors||0;$('#cpu').textContent=`${Math.round(state.metrics?.cpuPct||0)}%`;draw();}
async function load(){const health=await fetch('/health').then(r=>r.json());paused=health.paused;const snapshot=await fetch('/snapshot').then(r=>r.json());state=snapshot.state; $('#status').textContent=paused?'Collection paused — city is resting':'Live on 127.0.0.1 — observing sanitized activity';$('#pause').textContent=paused?'Resume collection':'Pause collection';paint();const ws=new WebSocket(`ws://${location.host}/events?afterSeq=${snapshot.lastSequence||0}`);let snapTimer=null;const refreshSnap=()=>{clearTimeout(snapTimer);snapTimer=setTimeout(()=>fetch('/snapshot').then(r=>r.json()).then(s=>{state=s.state;paint()}),100)};ws.onmessage=({data})=>{const message=JSON.parse(data);if(message.kind==='event') refreshSnap();if(message.kind==='control'){paused=message.paused;$('#pause').textContent=paused?'Resume collection':'Pause collection';$('#status').textContent=paused?'Collection paused — city is resting':'Live on 127.0.0.1 — observing sanitized activity'}};ws.onclose=()=>setTimeout(load,1500)}
$('#pause').onclick=async()=>{paused=!paused;await fetch('/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({paused})})};$('#demo').onclick=async()=>{const event={v:1,id:crypto.randomUUID(),ts:Date.now(),hostId:'local',sessionId:'demo',type:'shell.command.finished',payload:{command:'npm',subcommand:'test',category:'test',cwdKey:'path_manual',exitCode:Math.random()>.2?0:1,durationMs:140}};await fetch('/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(event)})};resize();load().catch(()=>$('#status').textContent='Relay is unavailable. Run npm run dev.');
