import { placeBuildings } from './layout.mjs';

const canvas = document.querySelector('#city'); const ctx = canvas.getContext('2d');
const TILE_X = 2; const TILE_Y = 1; const PAD = 28; const GUTTER = 220;
const colors = { git: '#8a6cff', test: '#47d9e4', build: '#ffb75f', package: '#ffb75f', container: '#b4e66e', sensitive: '#55505f', office: '#ff718f', other: '#8a6cff', shell: '#8a6cff' };
let state = { commands: 0, commits: 0, errors: 0, metrics: { cpuPct: 0, memoryPct: 0 }, districts: {}, buildings: {}, incidents: [], startedAt: Date.now() };
let paused = false; let offset = 0; let renderedScale = 20;
const $ = (id) => document.querySelector(id);
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
function project(x, y, z, scale) { return [((canvas.clientWidth - GUTTER) / 2) + (x - y) * TILE_X * scale + offset * (scale / 20), canvas.clientHeight * .72 + (x + y) * TILE_Y * scale - z * scale]; }
function poly(points, fill, stroke) { ctx.beginPath(); points.forEach(([x, y], i) => i ? ctx.lineTo(x, y) : ctx.moveTo(x, y)); ctx.closePath(); if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.stroke(); } }
function dims(building) { return { w: building.kind === 'build' || building.kind === 'package' ? 1.72 : .82, d: building.kind === 'build' || building.kind === 'package' ? .82 : .82, h: Math.min(240, 20 + (building.targetHeight || 2) * 7) / 20 }; }
function faces(x, y, z, w, d, h) { const a = project(x, y, z, renderedScale), b = project(x + w, y, z, renderedScale), c = project(x + w, y + d, z, renderedScale), e = project(x, y + d, z, renderedScale); const at = project(x, y, z + h, renderedScale), bt = project(x + w, y, z + h, renderedScale), ct = project(x + w, y + d, z + h, renderedScale), et = project(x, y + d, z + h, renderedScale); return { a, b, c, e, at, bt, ct, et }; }
function building(item) {
  const { x, y, building: b } = item; const { w, d, h } = dims(b); const f = faces(x - w / 2, y - d / 2, 0, w, d, h); const color = colors[b.kind] || colors.other;
  if (b.pending) { poly([f.a, f.b, f.bt, f.at], null, '#d8d1ff'); poly([f.b, f.c, f.ct, f.bt], null, '#d8d1ff'); poly([f.at, f.bt, f.ct, f.et], null, '#d8d1ff'); return; }
  poly([f.a, f.b, f.bt, f.at], `${color}aa`); poly([f.b, f.c, f.ct, f.bt], `${color}66`); poly([f.at, f.bt, f.ct, f.et], color);
  if (b.kind !== 'sensitive') for (let z = .18; z < h - .1; z += .3) { const p = project(x - w / 2, y - d / 2, z, renderedScale); ctx.fillStyle = '#fff0a9b8'; ctx.fillRect(p[0] + renderedScale * .14, p[1] + renderedScale * z * .06, Math.max(2, renderedScale * .055), Math.max(2, renderedScale * .055)); }
  if (b.kind === 'git') { const p = project(x, y, h + .32, renderedScale); const top = project(x, y, h, renderedScale); ctx.strokeStyle = '#ede8ff'; ctx.beginPath(); ctx.moveTo(...top); ctx.lineTo(...p); ctx.stroke(); }
  if (b.kind === 'test') { const p = project(x, y, h + .14, renderedScale); ctx.fillStyle = b.health < 100 ? '#ff635d' : '#9df278'; ctx.beginPath(); ctx.arc(...p, Math.max(3, renderedScale * .1), 0, Math.PI * 2); ctx.fill(); }
  if (b.kind === 'container') for (let i = 0; i < 2; i++) { ctx.strokeStyle = '#0b092099'; const p = project(x - w / 2, y - d / 2, h * ((i + 1) / 3), renderedScale); const q = project(x + w / 2, y + d / 2, h * ((i + 1) / 3), renderedScale); ctx.beginPath(); ctx.moveTo(...p); ctx.lineTo(...q); ctx.stroke(); }
  if (b.kind === 'office') { ctx.strokeStyle = '#ffe1efaa'; for (let i = .25; i < h; i += .25) { const p = project(x - w / 2, y - d / 2, i, renderedScale); const q = project(x + w / 2, y - d / 2, i, renderedScale); ctx.beginPath(); ctx.moveTo(...p); ctx.lineTo(...q); ctx.stroke(); } }
  if (b.health < 100) { const p = project(x, y, h + .2, renderedScale); ctx.fillStyle = '#ff635d'; ctx.beginPath(); ctx.arc(...p, Math.max(4, renderedScale * .13), 0, Math.PI * 2); ctx.fill(); }
}
function layout() {
  const structures = Object.values(state.buildings); const cells = placeBuildings(structures.map((b) => b.id)); const values = [...cells.values()];
  const minCol = Math.min(-4, ...values.map((p) => p.col)); const maxCol = Math.max(4, ...values.map((p) => p.col)); const minRow = Math.min(-3, ...values.map((p) => p.row)); const maxRow = Math.max(3, ...values.map((p) => p.row));
  const cx = (minCol + maxCol) / 2; const cy = (minRow + maxRow) / 2;
  return { structures: structures.map((b) => ({ building: b, x: cells.get(b.id).col - cx, y: cells.get(b.id).row - cy })), minX: minCol - cx - 1, maxX: maxCol - cx + 1, minY: minRow - cy - 1, maxY: maxRow - cy + 1 };
}
function fit(items) {
  const points = []; for (const { x, y, building: b } of items) { const { w, d, h } = dims(b); for (const z of [0, h]) for (const xx of [x - w / 2, x + w / 2]) for (const yy of [y - d / 2, y + d / 2]) points.push([(xx - yy) * TILE_X, (xx + yy) * TILE_Y - z]); }
  if (!points.length) points.push([-10, -5], [10, 5]); const xs = points.map((p) => p[0]); const ys = points.map((p) => p[1]); const desired = clamp(Math.min((canvas.clientWidth - GUTTER - PAD * 2) / Math.max(1, Math.max(...xs) - Math.min(...xs)), (canvas.clientHeight - PAD * 2) / Math.max(1, Math.max(...ys) - Math.min(...ys))), 8, 40); renderedScale += (desired - renderedScale) * .15;
}
function drawGrid(l) { ctx.strokeStyle = '#55467d66'; ctx.lineWidth = 1; for (let col = Math.floor(l.minX); col <= Math.ceil(l.maxX); col++) { const a = project(col, l.minY, 0, renderedScale); const b = project(col, l.maxY, 0, renderedScale); ctx.beginPath(); ctx.moveTo(...a); ctx.lineTo(...b); ctx.stroke(); } for (let row = Math.floor(l.minY); row <= Math.ceil(l.maxY); row++) { const a = project(l.minX, row, 0, renderedScale); const b = project(l.maxX, row, 0, renderedScale); ctx.beginPath(); ctx.moveTo(...a); ctx.lineTo(...b); ctx.stroke(); } }
function weather() { const cpu = clamp((state.metrics?.cpuPct || 0) / 100, 0, 1); const memory = clamp((state.metrics?.memoryPct || 0) / 100, 0, 1); const gradient = ctx.createLinearGradient(0, 0, 0, canvas.clientHeight); gradient.addColorStop(0, `rgba(${30 + Math.round(cpu * 45)},18,70,.9)`); gradient.addColorStop(1, '#070615'); ctx.fillStyle = gradient; ctx.fillRect(0, 0, canvas.clientWidth, canvas.clientHeight); ctx.fillStyle = `rgba(220,225,255,${memory * .16})`; ctx.fillRect(0, canvas.clientHeight * .45, canvas.clientWidth, canvas.clientHeight * .55); ctx.fillStyle = `rgba(255,205,130,${.12 + cpu * .18})`; for (let i = 0; i < Math.round(cpu * 28); i++) ctx.fillRect((i * 97) % canvas.clientWidth, 40 + (i * 59) % (canvas.clientHeight * .55), 2, 2); }
function draw() { const l = layout(); fit(l.structures); weather(); drawGrid(l); l.structures.sort((a, b) => (a.x + a.y) - (b.x + b.y) || dims(a.building).h - dims(b.building).h || a.building.id.localeCompare(b.building.id)).forEach(building); ctx.fillStyle = '#ded5ff'; ctx.font = '11px ui-monospace,monospace'; if (!l.structures.length) ctx.fillText('Waiting for activity. Try: terminus emit git status 0 82', PAD, canvas.clientHeight - 28); else ctx.fillText(`${l.structures.length} ACTIVE STRUCTURES`, PAD, canvas.clientHeight - 28); if (paused) { ctx.fillStyle = 'rgba(8,7,20,.42)'; ctx.fillRect(0, 0, canvas.clientWidth, canvas.clientHeight); ctx.fillStyle = '#ded5ff'; ctx.font = '700 18px ui-monospace,monospace'; ctx.fillText('COLLECTION PAUSED', PAD, PAD + 20); } }
function resize() { const ratio = devicePixelRatio || 1; canvas.width = canvas.clientWidth * ratio; canvas.height = canvas.clientHeight * ratio; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); draw(); }
addEventListener('resize', resize); canvas.addEventListener('pointermove', (event) => { offset = (event.offsetX / canvas.clientWidth - .5) * 26; draw(); });
function paint() { $('#commands').textContent = state.commands || 0; $('#commits').textContent = state.commits || 0; $('#errors').textContent = state.errors || 0; $('#districts').textContent = Object.keys(state.districts || {}).length; $('#cpu').textContent = `${Math.round(state.metrics?.cpuPct || 0)}%`; const up = Math.max(0, Date.now() - (state.startedAt || Date.now())); $('#uptime').textContent = `${Math.floor(up / 60000)}m`; draw(); }
async function load() { const health = await fetch('/health').then((r) => r.json()); paused = health.paused; const snapshot = await fetch('/snapshot').then((r) => r.json()); state = snapshot.state; $('#status').textContent = paused ? 'Collection paused — city is resting' : 'Live on 127.0.0.1 — observing sanitized activity'; $('#pause').textContent = paused ? 'Resume collection' : 'Pause collection'; paint(); const ws = new WebSocket(`ws://${location.host}/events?afterSeq=${snapshot.lastSequence || 0}`); let timer; const refresh = () => { clearTimeout(timer); timer = setTimeout(() => fetch('/snapshot').then((r) => r.json()).then((s) => { state = s.state; paint(); }), 100); }; ws.onmessage = ({ data }) => { const message = JSON.parse(data); if (message.kind === 'event') refresh(); if (message.kind === 'control') { paused = message.paused; $('#pause').textContent = paused ? 'Resume collection' : 'Pause collection'; $('#status').textContent = paused ? 'Collection paused — city is resting' : 'Live on 127.0.0.1 — observing sanitized activity'; draw(); } }; ws.onclose = () => setTimeout(load, 1500); }
$('#pause').onclick = async () => { paused = !paused; await fetch('/control', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ paused }) }); };
$('#demo').onclick = async () => { const event = { v: 1, id: crypto.randomUUID(), ts: Date.now(), hostId: 'local', sessionId: 'demo', type: 'shell.command.finished', payload: { command: 'npm', subcommand: 'test', category: 'test', cwdKey: 'path_0000000000000000', exitCode: Math.random() > .2 ? 0 : 1, durationMs: 140 } }; await fetch('/events', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(event) }); };
resize(); load().catch(() => $('#status').textContent = 'Relay is unavailable. Run npm run dev.');
